export default {
  login: "Alaa-Eldeyn",
  id: 93477209,
  node_id: "U_kgDOBZJZWQ",
  avatar_url: "https://avatars.githubusercontent.com/u/93477209?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Alaa-Eldeyn",
  html_url: "https://github.com/Alaa-Eldeyn",
  followers_url: "https://api.github.com/users/Alaa-Eldeyn/followers",
  following_url:
    "https://api.github.com/users/Alaa-Eldeyn/following{/other_user}",
  gists_url: "https://api.github.com/users/Alaa-Eldeyn/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Alaa-Eldeyn/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Alaa-Eldeyn/subscriptions",
  organizations_url: "https://api.github.com/users/Alaa-Eldeyn/orgs",
  repos_url: "https://api.github.com/users/Alaa-Eldeyn/repos",
  events_url: "https://api.github.com/users/Alaa-Eldeyn/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Alaa-Eldeyn/received_events",
  type: "User",
  site_admin: false,
  name: "Alaa Eldeyn",
  company: null,
  blog: "https://www.instagram.com/3lwa88",
  location: "Egypt, Assiut ",
  email: null,
  hireable: null,
  bio: "Front-end developer",
  twitter_username: null,
  public_repos: 23,
  public_gists: 0,
  followers: 6,
  following: 4,
  created_at: "2021-10-31T13:12:23Z",
  updated_at: "2023-07-11T11:59:20Z",
};